/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docsSidebar: [
    { type: 'category', label: 'PB', items: [{ type: 'autogenerated', dirName: 'pb' }] },
    { type: 'category', label: 'PRD', items: [{ type: 'autogenerated', dirName: 'prd' }] },
    { type: 'category', label: 'ADR', items: [{ type: 'autogenerated', dirName: 'adr' }] },
    { type: 'category', label: 'AC', items: [{ type: 'autogenerated', dirName: 'ac' }] },
    {
      type: 'category',
      label: 'Histórias',
      items: [{ type: 'autogenerated', dirName: 'historias' }],
    },
  ],
};

module.exports = sidebars;
